connect_ip = "127.0.0.1:25565"
listen_ip = "127.0.0.1:25555"
parsing_packets = ["*", "Handshake", "LoginSuccess", "Disconnect", "EncResponse", "SetCompression", "StatusPong"]
printing_packets = ["Handshake", "LoginStart", "LoginSuccess", "SpawnLivingEntity"]
